### ISSUE TITLE
iOS build errors after Upgrading to 6.0.0

### ISSUE THREAD

**Issue by yanush** [thebergamo/react-native-fbsdk-next#138] opened 2021-11-17 13:32 UTC
## 🐛 Bug Report
After upgrading to 6.0.0 (from 5.0.0) I get these two build errors in ios:

Undefined symbol: _OBJC_CLASS_$_FBSDKAuthenticationToken
Undefined symbol: _OBJC_CLASS_$_FBSDKLoginConfiguration

## Environment
System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Memory: 5.88 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment] 2021-11-17 13:59
Just a note that I don't think node v16 is fully working with react-native yet, careful there though your mileage may vary
JDK8 is not working fully with Android 31, so careful there in the other direction (JDK11 better)

That aside, `npx react-native-clean-project` and try again ?
This is definitely building and working here - we test it on every commit https://github.com/thebergamo/react-native-fbsdk-next/runs/4224610706?check_suite_focus=true

Somewhere in between our CI setup and your project setup there is a difference that is causing this :thinking:

**Comment by yanush** [comment] 2021-11-17 14:29
Downgrading back to 5.0.0 seems to fix the build issues, so...
Not really sure what's the problem...

**Comment by mikehardy** [comment] 2021-11-17 15:09
Try the example app. 

> Somewhere in between our CI setup and your project setup there is a difference that is causing this thinking

**Comment by jihokim2** [comment] 2021-11-22 01:22
I met same problem. Log is like this.
<unknown>:0: error: module map file '/Library/Developer/Xcode/DerivedData/AlbamOwner-buamgdsvqtzqekfxamvfomyrecji/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
<unknown>:0: error: module map file '/Library/Developer/Xcode/DerivedData/AlbamOwner-buamgdsvqtzqekfxamvfomyrecji/Build/Products/Debug-iphonesimulator/FBSDKLoginKit/FBSDKLoginKit.modulemap' not found
<unknown>:0: error: module map file '/Library/Developer/Xcode/DerivedData/AlbamOwner-buamgdsvqtzqekfxamvfomyrecji/Build/Products/Debug-iphonesimulator/FBSDKShareKit/FBSDKShareKit.modulemap' not found

**Comment by mikehardy** [comment] 2021-11-22 03:21
@jihokim2 that's usually an ios version mismatch between podfile (maybe 11? or 12) and project settings in Xcode (usually left on 10). This is gotten me  before

**Comment by jihokim2** [comment] 2021-11-23 02:07
@mikehardy But until version 5.0.0, it works fine.

**Comment by mikehardy** [comment] 2021-11-23 02:30
Release notes indicate there was a minimum version bump right? My point stands.

**Comment by thebergamo** [comment] 2021-12-14 08:16
As we're following semver, once we have a major release it means that there is some Breaking change, I would advice to maybe try to reinstall all dependencies related to this module and confirm that the integration works fine.

**Comment by swrobel** [comment] 2021-12-14 19:45
I can confirm a similar issue to @jihokim2. I went from 4.6.0 straight to 6.1.1 and started encountering this build error:

```
fatal error: module map file '<snip>/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
```

My build target was and still is 11.0, and it's consistent from the podfile to my xcode project. I reverted to 5.0.0 and it just built without issue. 

Macbook Pro 14" M1 Max, macOS 12.1, XCode 13.2

**Comment by mikehardy** [comment] 2021-12-14 20:35
and yet...the example still builds fine? No reproduction == no ability to help unfortunately. I did actually re-reproduce this personally when I had an ios version mismatch but if you don't have that issue @swrobel then I dunno. 

As far as reproduction goes, the example isn't some monolithic thing that is impossible to reproduce itself. The construction of the example itself is reproducible, it's a script https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

And it all works? Not sure what more I can do

**Comment by swrobel** [comment] 2021-12-14 22:23
I appreciate the difficulty helping, @mikehardy, and very much appreciate the effort. I was indeed able to archive the example app (with hermes enabled) without issue, so it seems that it's something specific to my project. What that could be, I have no idea as I've tried:

- Looking at the diff between 5.0.0 and 6.1.1 and not much has changed in this package that makes me think it would introduce some such error
- Looked on the facebook-ios-sdk issues to see if maybe it's something that exists upstream, but saw no other reports there
- Tried changing my Podfile's `post_install` block to match the one on the example app

I'm pretty much banging my head against the wall at this point, so it looks like I'm sticking with 5.0.0 for now.

**Comment by mikehardy** [comment] 2021-12-14 23:15
my last gasp there would be to use a postinstall to forcibly converge all target configs to your desired deployment - a bit crude, but maybe that works? there are snippets on the net for this

**Comment by thebergamo** [comment] 2021-12-15 16:36
In this case I believe we're good to close this issue. 
Just in case you're facing such issues, refer to https://github.com/thebergamo/react-native-fbsdk-next/issues/138#issuecomment-993959576

**Closed by thebergamo** 2021-12-15 16:36 UTC
Labels: question

**Comment by yanush** [comment] 2021-12-16 11:35
So just incase anyone else is encountering this issue, I was able to fix it by setting "Build Settings - Build Options - Enable Bitcode" to Yes (which is the default template but for some reason it was set to No in my project)

**Comment by swrobel** [comment] 2022-02-04 20:11
I was able to fix my issue using [these very helpful instructions](https://github.com/facebook/facebook-ios-sdk/issues/2016#issuecomment-1030209232), although in my case the offending references to modulemaps were in `OTHER_CFLAGS`.
