### ISSUE TITLE
Facebook SDK Integration Issue in React Native App for iOS 14+

### ISSUE THREAD

**Issue by qsales2022** [thebergamo/react-native-fbsdk-next#543] opened 2024-08-17 10:17 UTC
## Environment

# Facebook SDK Integration Issue in React Native App for iOS 14+

I'm experiencing an issue with Facebook SDK integration in my React Native app. The SDK is working correctly on Android and iOS versions below 14, but it's not functioning properly on iOS 14 and above. Here's what I've implemented so far:

## AppDelegate.mm

```objc
#import <React/RCTBundleURLProvider.h>
#import <AuthenticationServices/AuthenticationServices.h>
#import <SafariServices/SafariServices.h>
#import <FBSDKCoreKit/FBSDKCoreKit-Swift.h>
#import <FBAEMKit/FBAEMKit-Swift.h>
#import <React/RCTLinkingManager.h>
#import <AppTrackingTransparency/AppTrackingTransparency.h>
#import <AdSupport/AdSupport.h>

// In didFinishLaunchingWithOptions:
[[FBSDKApplicationDelegate sharedInstance] application:application
                       didFinishLaunchingWithOptions:launchOptions];

if (@available(iOS 14, *)) {
  [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
    // Handle tracking authorization status if needed
  }];
}

return [super application:application didFinishLaunchingWithOptions:launchOptions];

// OpenURL method
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [FBAEMReporter configureWithNetworker:nil appID:@"YOUR_APP_ID" reporter:nil];
  [FBAEMReporter enable];
  [FBAEMReporter handle:url];
  
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

## Podfile

```ruby
pod 'FBSDKCoreKit', '~> 17.0.0'
pod 'FBSDKLoginKit', '~> 17.0.0'
pod 'FBSDKShareKit', '~> 17.0.0'
```

## Info.plist

I've added the necessary Facebook-related keys and values to my Info.plist file, including:

- FacebookAdvertiserIDCollectionEnabled
- FacebookAppID
- FacebookAutoLogAppEventsEnabled
- FacebookClientToken
- FacebookDisplayName
- LSApplicationQueriesSchemes (for Facebook-related URL schemes)
- NSUserTrackingUsageDescription

## React Native Package

I'm using `react-native-fbsdk-next` version 13.0.0 in my project.

Despite these implementations, the Facebook SDK is not working on iOS 14 and above. What could be the issue, and how can I resolve it?

**Comment by ellowwwteam** [comment] 2024-08-20 04:57
![Screenshot from 2024-08-20 10-22-58](https://github.com/user-attachments/assets/59a73e30-37f1-4e9b-b5a6-b4d22a44f3ff)

Same issue here and how to resolve it? Any solution for this issue?

**Comment by i-ked-ii** [comment] 2024-09-10 02:34
Now facebook needs upgrade SDK version iOS v17.0.3

![Screenshot 2567-09-10 at 09 30 52](https://github.com/user-attachments/assets/d96e2ec8-0685-4081-a5d0-f766320dc187)

**Comment by ankitbacancy** [comment] 2024-09-20 12:17
@qsales2022 Have you resolved it ? If yes, could you please let me know how did you do it ?

**Comment by mikehardy** [comment] 2024-09-30 23:21
I believe these are different issues.

Original poster says it simply isn't working. I can't reproduce that. It works fine for me from the example app here on iOS 14+ and in my work app. So I'm going to close the issue as I cannot reproduce.

Other posters have hijacked the thread to say they want the ios SDK updated. That's been done in other pull requests

**Closed by mikehardy** 2024-09-30 23:21 UTC
