### ISSUE TITLE
Cannot build ios with v5.0.0, "No known class method for selector 'initializeSDK'"

### ISSUE THREAD

**Issue by uloco** [thebergamo/react-native-fbsdk-next#131] opened 2021-11-12 19:01 UTC
## 🐛 Bug Report
When trying to build ios app with v5.0.0 I get the following error in XCode
<img width="878" alt="image" src="https://user-images.githubusercontent.com/8818340/141520699-02230699-dd22-4ddf-b395-fd970e45cc62.png">

With the v4.6.0 everything was working fine.

I deleted and reinstalled node_modules / pods and removed podfile.lock etc.
Nothing helped...

## Environment

System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 134.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/j5/ckgkc5b95wb6p5vhwt_h9dyr0000gn/T/fnm_multishells/22085_1636740599654/bin/node
    Yarn: Not Found
    npm: 8.1.3 - /var/folders/j5/ckgkc5b95wb6p5vhwt_h9dyr0000gn/T/fnm_multishells/22085_1636740599654/bin/npm
    Watchman: 2021.11.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by uloco** [comment] 2021-11-12 19:03
The changelog of facebook-ios-sdk here:
https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#900
Maybe this helps...

**Comment by fierysolid** [comment] 2021-11-12 20:30
I get this same error even though I've confirmed that the method does exist inside FB core pods

**Comment by mikehardy** [comment] 2021-11-12 21:50
How does the example app work for you? I need someone to try it and let me know, because I built that thing a billion times while doing the forward port to facebook-ios-sdk v11 - very curious for results
You may like `npx react-native-clean-project` as a thing to try as well

**Comment by mikehardy** [comment] 2021-11-12 21:53
Oh wait! This is different. There's just a new way to initialize, you probably should not be doing it there in your AppDelegate.m - you probably should be using our JS hook:

https://github.com/thebergamo/react-native-fbsdk-next#platform-neutral-sdk-initialization

However, you *can* do that and the documentation is now out of date. Should look like 
https://github.com/thebergamo/react-native-fbsdk-next/pull/125/files#diff-be03dd17b2019e2f4ddd389c2a9dbfceaf560485d2111c8462bc0c8530695878R48

Someone please try that and let me know!

**Comment by mikehardy** [comment] 2021-11-13 13:23
I have a PR that I will merge shortly with updates to the README for the new SDK init style and I've updated the release notes to contain this extra breaking change. Thanks for bringing this up! We probably would not have noticed it otherwise.

I will close this as I presume we have the fix for it, but if it needs further work we may reopen

**Closed by mikehardy** 2021-11-13 13:23 UTC
