### ISSUE TITLE
Facebook says my SDK is outdated when it's not (16.* SDK bug?)

### ISSUE THREAD

**Issue by DavideValdo** [thebergamo/react-native-fbsdk-next#452] opened 2023-08-28 16:43 UTC
## 🐛 Bug Report
<img width="964" alt="Screenshot 2023-08-28 at 18 39 19" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/26572302/fecd9d7d-2ca7-48d1-b63f-6203091b7270">

This seems to be a bug on the SDK side: https://developers.facebook.com/community/threads/174497285531587/
Reverting to 15.2.0 seems to solve the issue.

## To Reproduce
Install a version of this lib using SDK 16.*

## Expected Behavior
No message should be shown.

## Environment
```
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 58.38 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/mdev/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.4 is now available (your project is running on v0.70.3).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.3
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

**Comment by eisayfutdinova** [comment] 2023-08-30 06:01
Same Issue +1

**Comment by 1jmj** [comment] 2023-09-13 09:18
+1

**Comment by MamyChow** [comment] 2023-09-15 11:05
same issue +1

**Comment by dennis-gonzales** [comment] 2023-09-21 06:48
+1

**Comment by kamilcessak0** [comment] 2023-09-21 08:51
+1

**Comment by stefanahman** [comment] 2023-09-21 12:05
Same for me as well, but it says that the latest Android version is 13.0.0.

<img width="273" alt="image" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/1053201/84a53788-9e2c-486a-93e9-7ad78a7fe646">
<br><br>
Is it a problem that a later version is used?

**Comment by almitar** [comment] 2023-10-12 23:28
Anyone knows how to fix it?

**Comment by Jakob-k** [comment] 2023-10-13 10:09
I am also stuck with this

**Comment by mikehardy** [comment] 2023-10-18 22:04
+1s are worse then useless in an open source context, as they generate attention-robbing notifications. Please avoid them, use reactions.

PRs are happily accepted, it could be that firebase-ios-sdk has an update and we could adopt it here. It could be that our documentation needs a fix to let you know this is ignorable (along with a link to the upstream documentation). But other than that I'm not sure what the expectation here is with regard to "this change will fix it", so an issue and a stream of +1s are not useful.

PRs to versions, PRs to code, PRs to docs, one of those will move this forward

**Comment by davidg327** [comment] 2023-10-30 14:34
You can see and review and with the new version that there is, there is a variable called setClienteToken, if you put the secret token there, it starts serving me like this and started taking the events.

This is how I have the code in the app.tsx, I know that having the client ID may not be necessary but I put it in by default

`useEffect(() => { Settings.initializeSDK() Settings.setAppID('') Settings.setClientToken('') }, [])`

I hope it works for you

**Comment by torrrrzz** [comment] 2023-10-31 04:47
hi @DavideValdo how do you revert the version to 15.2.0, Im thinking to revert for now because my app is using only the auto log events which is app install and app activate.

**Comment by PedroDmian** [comment] 2023-10-31 05:59
Through trial and error.

I think I've found a temporary solution by downgrading the sdk version. I don't know if this is a solution but it works for me for the moment.

app\build.gradle
`implementation 'com.facebook.android:facebook-android-sdk:14.1.1'`

Package.json

`"react-native-fbsdk-next": "^10.1.0",`


App.js

`useEffect(() => {`
`    Settings.initializeSDK();`
`    Settings.setAppID('ID');`
`  }, []);`

**Comment by kamil-floqsta** [comment] 2023-11-03 10:38
+1
is there any fix coming?

**Comment by mikehardy** [comment] 2023-11-03 14:55
I don't know, @kamil-floqsta I'm fully +1 on you proposing a PR to fix it. Thanks!

**Comment by mikehardy** [comment] 2023-11-07 17:15
Anyone try the latest SDK 16.2.1 via patch-package?

https://github.com/facebook/facebook-ios-sdk/releases

Could fix the problem, and we could take a PR to merge it if anyone cared to do the work to test things...

We're still on 16.1.3 here https://github.com/thebergamo/react-native-fbsdk-next/blob/36a762af896bc4ed2dd08b1f361267f107e830ed/react-native-fbsdk-next.podspec#L4

**Comment by hasretozkan** [comment] 2023-11-07 23:31
+1 is there any fix for this?

**Comment by mikehardy** [comment] 2023-11-08 01:54
Hey @hasretozkan we're all just +1 waiting on you to post a PR updating the native ios SDK after you test the new version to see how it goes +1 +1 +1 yeah

**Comment by kamilcessak0** [comment] 2023-11-09 10:13
Ekhm.. Check guys that u signIn with account that is allowed in development mode on facebook developer account. I was getting an error with app inactive and outdated sdk because i tried to signIn with my personal fb account while i have development mode on facebook developer. When this mode is enabled not live mode u can only signIn with administrator fb account. It worked me with fbsdk-next v 2.1.0 and patched fbsdkversion 16.2.1

**Comment by FondueBug** [comment] 2023-11-29 15:04
So there was a issue with IOS and Android where the meta dashboard stated that I had a outdated SDK version.
I have fixed that temporary on IOS by downgrading to react-native-fbsdk-next 11.3.0.
However this did not fix the issue with android, it still states that there is outdated SDK.
@stefanahman have you been able to fix this issue?

**Comment by stefanahman** [comment] 2023-12-01 05:22
It took some time before the changes comes through I think. But now it looks like this and I haven't touched it since:

<img width="592" alt="image" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/1053201/19e9c98a-785b-411a-85af-986d1327a8b4">

I'm using version 11.3.0.

**Comment by stefanahman** [comment] 2023-12-01 13:53
> @stefanahman so you are using an outdated version which includes an outdated version of the SDK, and it doesn't show the error that everyone indicates is happening with the updated version (v12+ here, using SDKs v16+)?
> 
> 
> 
> That's expected, and doesn't help people using v12+ (v16+ of native SDKs) here

Yes, I too, had to downgrade to get something to work.
This is just a workaround and I haven't solved the root cause. Sorry if I wasn't clear enough.

All I did was to confirm that the downgrade worked.

**Closed** 2024-01-09 04:32 UTC
Labels: wontfix

**Comment by chucnqicetea** [comment] 2024-05-30 13:20
I had an issue with the Android version showing the v0.0.0, i tried to downgrade the version v11, v10, v9 but they didn't work for me. So, i ended up with changing the version of fb-android-sdk in the build.gradle in the node_modules for 14.1.1, then run the new app and the version of Android sdk got updated.
Hope this helps.

![image](https://github.com/thebergamo/react-native-fbsdk-next/assets/108801770/87225713-469e-4036-b118-9a527bb3d7f5)
