### ISSUE TITLE
IOS build failed with FBSDKCoreKit/FBSDKCoreKit.modulemap not found 

### ISSUE THREAD

**Issue by sonnv106** [thebergamo/react-native-fbsdk-next#502] opened 2024-03-13 18:16 UTC
I'm receiving the error 'FBSDKCoreKit/FBSDKCoreKit.h' file not found always when trying to run the app on my iPhone from xCode.

But when I run it from terminal, with the react-native run-ios it's working normally, as expected.

I already tried to update podfile, rerun it and a lot of other things and nothing solved the problem.

I must run this on device for testing in app purchase in another part of the app.

The import seems to be correct but does not work. 

Xcode: 14
Mac: Apple m1 2020
"react-native": "0.73.2"
"react-native-fbsdk-next": "^12.1.4"

![Screen Shot 2024-03-14 at 01 16 05](https://github.com/thebergamo/react-native-fbsdk-next/assets/49037752/48e6331c-f68f-4ed3-8a38-55febd9e6b21)

**Comment by mikehardy** [comment] 2024-04-11 13:57
Hi there - I don't reproduce this building the example included in this repository - either debug or release mode - using Xcode instead of the command line.

Since the example in the repo is a https://stackoverflow.com/help/minimal-reproducible-example that's usually pretty conclusive for me that things are working, and typically points to some sort of project-specific problem which you'll need to analyze locally

If you can start from `npx react-native@latest init` and add this module, then reproduce the problem, you might be able to post that as a reproduction and attract someone to look at it - but in the presence of a working repro with the example and no non-working repro, I'm going to close this

**Closed by mikehardy** 2024-04-11 13:57 UTC
