### ISSUE TITLE
[iOS] App crashes on startup on 4.3.0 (probable incompatibility with deprecated MixPanel messaging module)

### ISSUE THREAD

**Issue by migue1s** [thebergamo/react-native-fbsdk-next#54] opened 2021-06-11 18:47 UTC
## 🐛 Bug Report

App is crashing on app startup on iOS.

```
+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x107ac4aa8
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x107ac4aa8'
*** First throw call stack:
(0x1a46bd9d8 0x1b8a40b54 0x1a45d2070 0x1a46c001c 0x1a46c1f8c 0x1040f1558 0x107a1e488 0x10a811528 0x10a8208a8 0x10a811528 0x10a81f994 0x1a463d5e0 0x1a4637a88 0x1a4636ba0 0x1bb39c598 0x1a6f282f4 0x1a6f2d874 0x10276caf8 0x1a4315568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x107ac4aa8'
terminating with uncaught exception of type NSException
```

## To Reproduce

- Update react-native-fbsdk-next from 4.2.0 to 4.3.0
- pod update FBSDKCoreKit FBSDKLoginKit FBSDKShareKit
- build and run

## Expected Behavior
- App works as before

## Actual Behavior
- App crashes on startup

## Code Example

App is currently only initializing the SDK.

```
import { Settings } from 'react-native-fbsdk-next';

Settings.initializeSDK();
```

## Environment
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 270.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.2 - /var/folders/py/_bdk2p1n13v1hc7fq1bhs2000000gn/T/yarn--1623436645989-0.8183305738118558/node
    Yarn: 1.22.10 - /var/folders/py/_bdk2p1n13v1hc7fq1bhs2000000gn/T/yarn--1623436645989-0.8183305738118558/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.2/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found // using 1.10.1 with bundler
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-S | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment] 2021-06-11 20:08
I just attempted to reproduce this in my work project and it all worked fine.
`npx react-native-clean-project` perhaps?

**Comment by Vitiell0** [comment] 2021-06-14 19:24
Just upgraded and am also experiencing this same issue. App crashes immediately on launch when building for release. Works fine when building debug for dev. 

```
2021-06-14 14:00:14.565685-0500[1765:2023831] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x1057cbb00'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20431c48 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff204274cf ___forwarding___ + 1455
	4   CoreFoundation                      0x00007fff204297a8 _CF_forwarding_prep_0 + 120
	5   App Name                            0x0000000103d34999 +[FBSDKSwizzler swizzleSelector:onClass:withBlock:named:] + 28
	6   App Name                            0x0000000103e4e24a __38-[Mixpanel setupAutomaticPushTracking]_block_invoke + 618
	7   libdispatch.dylib                   0x0000000107b3c74e _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000107b4ba2a _dispatch_async_and_wait_invoke + 175
	9   libdispatch.dylib                   0x0000000107b3c74e _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000107b4ab3f _dispatch_main_queue_callback_4CF + 1152
	11  CoreFoundation                      0x00007fff203908f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x00007fff2038b169 __CFRunLoopRun + 2781
	13  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	14  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	15  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	16  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	17  App Name                            0x0000000103c892a5 main + 80
	18  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[MPSwizzler swizzleSelector:onClass:withBlock:named:async:]: unrecognized selector sent to class 0x1057cbb00'
terminating with uncaught exception of type NSException
```

I am wondering if this is a conflict with Mixpanel and FBSDK since the trace mentions `0x0000000103e4e24a __38-[Mixpanel setupAutomaticPushTracking]_block_invoke + 618` and found this issue that may be related: https://github.com/mixpanel/mixpanel-iphone/issues/934

**Comment by migue1s** [comment] 2021-06-14 19:26
Validating that I also have mixpanel as a dependency.

**Comment by mikehardy** [comment] 2021-06-14 19:47
Interesting. I just read up on that, and it appears that's a "closed -> won't fix" because they're killing messaging in their product, which kills the need for them to swizzle, which should mean this works fine here.

They don't appear to include Firebase Messaging in their list of providers they prefer (whatever that means? I assume a nicer integration) but I can confirm at least that this module in it's current version and react-native-firebase (using messaging) appear to work fine together at the moment.

I'm not sure there is any action at all that this module can take though. This is a low-level (that is: the underlying SDK) iOS incompatibility where one party (MixPanel) has clearly indicated they're not going to fix anything because it's going away anyway.

Seems like this should also close as resolved won't fix, but it should help future folks if they are also using MixPanel and see a crash.

**Comment by Vitiell0** [comment] 2021-06-14 20:27
@mikehardy thanks for digging into it. It looks like there is an official Mixpanel library out now `mixpanel-react-native` where we are using `react-native-mixpanel` which is an unofficial wrapper. Going to try switching to that and see if it gets us around that issue and will let yall know.

**Comment by Vitiell0** [comment] 2021-06-14 20:54
@mikehardy just a note - Mixpanel was working fine with the original `react-native-fbsdk` package. It was only when we upgraded to `fbsdk-next` that the issue started appearing. So wondering if the root of the issue is actually on the Mixpanel side or not.

**Comment by migue1s** [comment] 2021-06-14 21:10
Again, I found the same behavior as @Vitiell0, just validating this. (thanks for the input here! Been busy with other stuff)

**Comment by mikehardy** [comment] 2021-06-14 21:19
One of the main things this library did immediately was to update from facebook-ios-sdk  v8 to v9 and unfortunately that change is huge https://github.com/facebook/facebook-ios-sdk/compare/v8.2.0...v9.0.0

Based on the bisect work from @migue1s it appears that the difference is in the minor bump in this PR then https://github.com/thebergamo/react-native-fbsdk-next/pull/45

Lo and behold, a pile of swizzler changes https://github.com/facebook/facebook-ios-sdk/compare/v9.2.0...v9.3.0 (visible if you look at the files tab so you can see the diff then search for swizz)

What are they doing in there? Why isn't it compatible? No idea unfortunately, I don't use mixpanel so I don't see the incompatibility.

Not saying mixpanel is doing anything wrong per se, but it's definitely an interaction between the underlying SDKs, it's not something this module can do anything about

**Comment by migue1s** [comment] 2021-06-14 21:46
Makes sense, thanks so much for looking into this Mike! Feel free to tag as a `won't fix` given it's a bug outside of this lib @mikehardy

**Comment by mikehardy** [comment] 2021-06-14 22:40
I personally enjoy fixing things much more then I like resolving things won't fix, but I think it's the best path here. Can always reopen if there is new information and something actionable though, for sure. Cheers

**Closed by mikehardy** 2021-06-14 22:40 UTC
Labels: needs more info, no reproduction

**Comment by Vitiell0** [comment] 2021-06-15 16:14
@migue1s just wanted to report that by changing our app to use the new `mixpanel-react-native` package the issue is resolved for us.
