### ISSUE TITLE
[IOS] App Crash "dyld" error Library not loaded / upstream issue it seems

### ISSUE THREAD

**Issue by Pashkagreen** [thebergamo/react-native-fbsdk-next#324] opened 2022-10-07 12:34 UTC
## 🐛 Bug Report
 Hello guys. After adding all the staff im trying to launch my application, then it build successfully, and then immediately crashes, because due to stacktrace it cannot find FB libraries. Please help me, I know that the reason is in paths to libs but dont know how to fix it. Attach my code below

## To Reproduce

  Add everything following the docs
  -> build project

## Expected Behavior

  Successful app launching

## Code Example
Error-trace in Xcode:  

dyld[14149]: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/2309C386-5A39-46F4-86BD-454E538C473F/data/Containers/Bundle/Application/1F10C791-B1D9-492F-8D15-D94DC3B1FB97/bkkz.app/bkkz
  Reason: tried: '/Users/admin/Library/Developer/Xcode/DerivedData/bkkz-dfnyardsrennayetefqfyxjjgtud/Build/Products/Debug-iphonesimulator/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/Users/admin/Library/Developer/Xcode/DerivedData/bkkz-dfnyardsrennayetefqfyxjjgtud/Build/Products/Debug-iphonesimulator/PackageFrameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file),

--------------------------------------------------------------

My Podfile:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def mindbox_notifications
	pod 'MindboxNotifications'
	
 end

platform :ios, '12.0'

target 'bkkz' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
	
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'GoogleSignIn', '~> 6.2.2'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
	pod 'Mindbox'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKGamingServicesKit', '~> 15.0.0'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

  target 'bkkzTests' do
    inherit! :complete
    # Pods for testing
  end

	# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'MindboxNotificationServiceExtension' do
	mindbox_notifications
 end
	
 target 'MindboxNotificationContentExtension' do
	mindbox_notifications
 end
--------------------------------------------------------------------------

My AppDelegate: 

#import <Firebase.h>
#import "AppDelegate.h"
#import <React/RCTLinkingManager.h>
#import <RNAppsFlyer.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <FBSDKCoreKit/FBSDKCoreKit-swift.h>
#import <RNGoogleSignin/RNGoogleSignin.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
#import <YandexMapKit/YMKMapKitFactory.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@import Mindbox;
@import MindboxSdk;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
[[FBSDKApplicationDelegate sharedInstance] application:application
                       didFinishLaunchingWithOptions:launchOptions];

#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"bkkz"
                                            initialProperties:nil];

  // MINDBOX INTEGRATION
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
  [center requestAuthorizationWithOptions:(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge) completionHandler:^(BOOL granted, NSError * _Nullable error) {
    if (!error) {
      dispatch_async(dispatch_get_main_queue(), ^{
        [[UIApplication sharedApplication] registerForRemoteNotifications];
        [[Mindbox shared] notificationsRequestAuthorizationWithGranted:granted];
      });
    }
    else {
      NSLog(@"NotificationsRequestAuthorization failed with error: %@", error.localizedDescription);
    }
  }];

  // MINDBOX INTEGRATION
  if (@available(iOS 13.0, *)) {
		rootView.backgroundColor = [UIColor systemBackgroundColor];
    [[Mindbox shared] registerBGTasks];
  }
  else {
		rootView.backgroundColor = [UIColor whiteColor];
    [[UIApplication sharedApplication] setMinimumBackgroundFetchInterval:UIApplicationBackgroundFetchIntervalMinimum];
  }

  // MINDBOX INTEGRATION
  TrackVisitData *data = [[TrackVisitData alloc] init];
  data.launchOptions = launchOptions;
  [[Mindbox shared] trackWithData:data];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// MINDBOX INTEGRATION
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  TrackVisitData *data = [[TrackVisitData alloc] init];
  data.universalLink = userActivity;
  [[Mindbox shared] trackWithData:data];
  return YES;
}

// MINDBOX INTEGRATION
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
  completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionBadge);
}

// MINDBOX INTEGRATION
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [[Mindbox shared] apnsTokenUpdateWithDeviceToken:deviceToken];
}

// MINDBOX INTEGRATION
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
  [MindboxJsDelivery emitEvent:response];
  [[Mindbox shared] pushClickedWithResponse:response];
  TrackVisitData *data = [[TrackVisitData alloc] init];
  data.push = response;
  [[Mindbox shared] trackWithData:data];
  completionHandler();
}

// MINDBOX INTEGRATION
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  [[Mindbox shared] application:application performFetchWithCompletionHandler:completionHandler];
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
    return YES;
  }
  
  if ([RNGoogleSignin application:application openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:application openURL:url options:options]) {
    return YES;
  }
  
  [[AppsFlyerAttribution shared] handleOpenUrl:url options:options];
 
  return NO;
}

@end

-----------------------------------------------------------------------

Also have added a bridging-header and try antoher variant with ~~~ installer.~~ in podfile, but didnt help.

Attach my settings in project build settings: 

## Environment
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 82.40 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/Desktop/bk-kz-mobile/node_modules/.bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2/13C90 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

<img width="736" alt="Снимок экрана 2022-10-07 в 15 33 12" src="https://user-images.githubusercontent.com/91741628/194554391-c0065ab6-7db1-4788-94af-caf32426cac1.png">

**Comment by Pashkagreen** [comment] 2022-10-07 13:22
Actually there are no such files in usr/lib/swift. In which way the FB-libraries should get into this folder?

**Comment by mikehardy** [comment] 2022-10-07 16:18
Hey, this is a mess, in your Podfile:

```ruby

pod 'GoogleSignIn', '> 6.2.2'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Mindbox'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKGamingServicesKit', '> 15.0.0'
pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
```

1) Do not add the FBSDK Pods directly, autolinking takes care of it (web search "react-native cli autolinking")
2) Do not add the Firebase SDKs directly, autolinking does that if you have react-native-firebase installed
3) and also, as the maintainer of react-native-firebase :wave: do not do that modular_headers stuff as an unsupported workaround to avoid `use_frameworks! :linkage => :static` in your Podfile, **you must include use_frameworks to use current react-native-firebase**

No idea what all the mindbox stuff is but your build failure is going to be a local problem in your local project and not our responsibility

We provide what is in effect a minimal example of integration + build, and it works successfully (https://stackoverflow.com/help/minimal-reproducible-example)

It's our example, and it's built by a script even, so you can try it yourself starting with `npx react-native init ...`: https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

Read that script and all the comments in it, they are useful

**Comment by HaidarZ** [comment] 2022-10-08 13:05
I've got the same error mentioned above although my Podfile is never touched, and everything is kept as the app was just initialized.

**Comment by Pashkagreen** [comment] 2022-10-08 13:13
> I've got the same error mentioned above although my Podfile is never touched, and everything is kept as the app was just initialized. The error appeared when I upgraded the library to version 11. My react native version is 0.69.6

thank man im try to downgrade lib version

**Comment by HaidarZ** [comment] 2022-10-08 13:24
> I've got the same error mentioned above although my Podfile is never touched, and everything is kept as the app was just initialized. The error appeared when I upgraded the library to version 11. My react native version is 0.69.6

Everything is back to normal after I've downgraded back to v10.1.0

**Comment by mikehardy** [comment] 2022-10-08 14:59
So our example script here is a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example)

And it works. So the burden of proof that there is an issue is on you, those having the problem.

Please also note that versions of everything are important (your Xcode, your pod version, your macOS and iOS versions where this happens, react-native versions, version of this library etc - https://stackoverflow.com/help/how-to-ask)

No comments here will help move this forward without a minimal reproducible example that shows the problem, wth information needed to run it and reproduce it.

Efficiently triaging issues and finding root causes is real work but it is how to move things forward. If anyone makes the effort, we might be able to pin this down to the exact reason it happens. Until then, the only reproducible example I've got is one that works.

**Comment by Pashkagreen** [comment] 2022-10-10 08:30
> So our [example script](https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh) here is a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example)
> 
> And it works. So the burden of proof that there is an issue is on you, those having the problem.
> 
> Please also note that versions of everything are important (your Xcode, your pod version, your macOS and iOS versions where this happens, react-native versions, version of this library etc - https://stackoverflow.com/help/how-to-ask)
> 
> No comments here will help move this forward without a minimal reproducible example that shows the problem, wth information needed to run it and reproduce it.
> 
> Efficiently triaging issues and finding root causes is real work but it is how to move things forward. If anyone makes the effort, we might be able to pin this down to the exact reason it happens. Until then, the only reproducible example I've got is one that works.

Dont know why, but downgrading to 8.0.0 has helped me. Maybe the problem was in mismatch between differents libs, pods etc. However, big thank to you, @mikehardy , for your advices and your creation!)

**Comment by EduCarloto** [comment] 2022-10-14 13:44
https://github.com/facebook/facebook-ios-sdk/issues/2121

**Comment by mikehardy** [comment] 2022-10-14 21:54
Oh that looks really subtle - I wonder what we need to do here in order to handle that? :thinking: here are the frameworks they mention:

https://github.com/facebook/facebook-ios-sdk/issues/2121#issuecomment-1277205187

But I thought we brought all of them in our podspec thus they should all be embedded already. I dunno - I still have no problem in a release version personally so I cannot triage. Good link though @EduCarloto

**Comment by mikehardy** [comment] 2022-10-17 03:23
This appears to be an upstream issue but it is affecting folks and generating duplicate issues. Going to reopen and pin it

**Comment by robsco** [comment] 2022-11-16 16:14
FYI, for anyone else googling...

Adding those FBSDKCoreKit, CoreKit_Basics fixed this for me, but only when including the GamingServices one - to FrameWorks, Libraries and Embedded Content.

from [](https://github.com/facebook/facebook-ios-sdk/issues/2121#issuecomment-1277205187)

This is all with a fresh new build on the latest RN - as I'm porting my existing app over, and switching to this lib instead of the original react-native-fbsdk one.

**Comment by KrisLau** [comment] 2022-11-18 15:23
@Pashkagreen @mikehardy Was this closed by mistake? Still seems to be occurring whenever I upgrade to >v11

**Comment by mikehardy** [comment] 2022-11-18 15:51
Original poster closed it but it does not seem to be resolved

**Comment by jessiealbarian** [comment] 2022-11-22 22:38
I had to downgrade react-native-fbsdk-next from v 11 to 10 and run a clean build for it to run successfully.
react-native: 0.67.2
react-native-fbsdk-next: 10.1.0

**Comment by jessiealbarian** [comment] 2022-11-22 22:59
@KrisLau I was able to upgrade react-native-fbsdk-next to v 12 by linking those 3 frameworks you mentioned and also changing my platform in my Podfile to: 
platform :ios, '12'

**Comment by mikehardy** [comment] 2022-11-27 01:30
:thinking: so at this point, we have a (kind of terrible looking, if I'm honest, but that is not your fault..) workaround, or otherwise it is perhaps best to stay on a previous version until the upstream SDK has some resolution I suppose. I'm sad this is happening but it still does not *really* seem to be in the control of this module.

Unless perhaps we could do some Podfile (or, from a module perspective: podspec) magic to get those frameworks linked for people as part of the normal pod install process?

**Comment by robsco** [comment] 2022-11-27 11:34
Out of interest, could you explain the issue, just to make all this less of a blackbox/black magic, for simple folk like me.

It'd be nice to understand just a little bit of why this is failing, especially if it may ever happen in the future, to save hours of Googling.

Pods, Podspec, linking, etc.  just a quick overview would be great.

**Comment by mikehardy** [comment] 2022-11-27 13:02
Sorry, I don't have the time for that. Each of the subjects is the kind of thing that requires actual reading and there's no shortcut to the actual knowledge as far as I know

**Comment by jackchengck** [comment] 2022-12-07 06:06
Is that any stable version of react-native-fbsdk-next can be used right now?
i have been burnout to trying to fix this on an urgent project

**Comment by KrisLau** [comment] 2022-12-07 14:22
@jackchengck either downgrade to v10 or follow the workaround:

- https://github.com/thebergamo/react-native-fbsdk-next/issues/324#issuecomment-1320583225

**Comment by phantrungviet98** [comment] 2023-01-06 07:31
i am facing the same issue. I am using Hackintosh, maybe it is the issue ? @Pashkagreen

**Comment by xeongm** [comment] 2023-01-16 13:45
Hi gays. I resolved problem.

**Comment by marquina-abreu** [comment] 2023-02-14 17:33
same error ....

**Closed** 2023-03-23 22:09 UTC
Labels: wontfix

**Comment by SalaarFiend** [comment] 2023-04-25 21:57
Hello!
I had the same problem, but I solved it and told about it [here](https://medium.com/@devsalaar/dyld-library-not-loaded-error-on-ios-react-native-fix-guide-bb0b6a91e85a).
I hope this helps someone!

**Comment by robsco** [comment] 2023-04-25 22:01
I may be mistaken but that looks completely unrelated, it's nothing to do with FBSDK.

**Comment by SalaarFiend** [comment] 2023-04-25 22:46
> I may be mistaken but that looks completely unrelated, it's nothing to do with FBSDK.

Hi, yes it is, there is no FBSDK
But it's more like an example, if you go through the steps in the guide, you can find the root of the problem

**Comment by phantrungviet98** [comment] 2023-05-26 13:14
Just updated cocoapods to latest version (1.12.1 now) and pod install again then the issue was gone guys

**Comment by robsco** [comment] 2023-05-26 14:47
I confirm that too, I was able to remove the embedding and signing in xcode and it all works fine.

**Comment by anieve01** [comment] 2023-11-24 00:28
I too just updated cocoapods to the latest version (1.14.3 now) and then the issue was gone. 
I'm using react native expo and I had the error below similar to the OP above and now this issue is resolved. 

```
npx expo prebuild --platform ios --clean
xed ios
```
Then in xcode run the app on a physical device. It worked.
Thanks @phantrungviet98  and @robsco 

```
dyld[17194]: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
Referenced from: <4654A647-5A89-30AA-9166-9FB5DEB44451> /private/var/containers/Bundle/Application/74FDD0B8-42AB-4AAE-A966-64D53039FE18/Surfn.app/Surfn
Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/74FDD0B8-42AB-4AAE-A966-64D53039FE18/Surfn.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/74FDD0B8-42AB-4AAE-A966-64D53039FE18/Surfn.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/74FDD0B8-42AB-4AAE-A966-64D53039FE18/Surfn.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/74FDD0B8-42AB-4AAE-A966-64D53039FE18/Surfn.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file)
```

**Comment by w4ndry** [comment] 2023-12-31 12:28
I use SDK 16.1.3, cocoapods-1.12.1,  and added FacebookGamingServices is working for me

<img width="884" alt="Screenshot 2023-12-31 at 19 25 08" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/22952485/447d3b85-c067-469e-aa29-650ac0effb9f">
