### ISSUE TITLE
Login is returning unsupported request error [LIKELY RESOLUTION: blocked app, you need to contact facebook support]

### ISSUE THREAD

**Issue by pisacode** [thebergamo/react-native-fbsdk-next#128] opened 2021-11-10 13:38 UTC
When users clicks to login with facebook on android, facebook servers return an error as follows: 

`"SERVER_ERROR: [code] 1675030 [message]: An error occurred during query [extra]: "`

And on IOS webview opens and when user clicks to connect, web views show the attached error. 
![Screen Shot 2021-11-08 at 13 40 18](https://user-images.githubusercontent.com/9843437/141123076-3e3ebefb-d508-461c-9780-7d74e3fdb628.png)

And all of this issues just appeared suddenly without any changes to code. 

Do you have any idea what might be the problem?

Thanks

**Comment by mikehardy** [comment] 2021-11-10 13:42
No I do not, sorry
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by meshaabi** [comment] 2021-11-10 14:53
I have been trying to investigate this issue since yesterday - It was initially raised by facebook who have disabled our app as our "login is not working" but we have not had any configuration changes on our end to have caused this.

others seem to also be facing this issue
https://stackoverflow.com/questions/69894453/facebook-login-was-disabled-and-now-it-throws-errors

Facebook support is being unresponsive, and we still do not have a resolution :/

**Comment by mikehardy** [comment] 2021-11-10 15:12
I have never seen facebook be responsive, actually :shrug: I guess that's what a few billion users does to response time :sweat_smile: 

This appears to be completely upstream, I'm not sure what we can do here.

I will say that perhaps adding your app client token to your Info.plist and AndroidManifest.xml will help, who knows? And iOS v9 is not new though it is all that is supported here until I release #125 which is pending a little more polish (almost done) on #127 - at that point the refresh_example.sh script will show how to do the full configuration from scratch (as a script, but with comments explaining each step) so perhaps something in there will help

But most likely it's something about your metadata in facebooks application definition / configuration screens, or just facebook themselves doing something difficult

**Comment by meshaabi** [comment] 2021-11-10 15:23
@mikehardy I actually tried the latest commit with 11.x from master yesterday and had the same issue. Im with you here, the problem is like upstream, also we are facing this on an iOS only app ( also the folk from the stackoverflow ticket seem to be using native sdk's directly ).

Thanks for the tip with client token, I'll give that a go and post and update or if we magically get a response back from facebook and manage to sort it out ✌️

**Comment by bsonmez** [comment] 2021-11-10 17:10
We have been getting the same issue for two days, and our application has been disabled because of this. Is there a chance the matter is related to the SDK?

**Comment by nazrdogan** [comment] 2021-11-10 17:16
+1

**Comment by meshaabi** [comment] 2021-11-10 17:18
> @mikehardy I actually tried the latest commit with 11.x from master yesterday and had the same issue. Im with you here, the problem is likely upstream, also we are facing this on an iOS only app ( + the folk from the stackoverflow ticket seem to be using native sdk's directly ).
> 
> Thanks for the tip with client token, I'll give that a go and post and update or if we magically get a response back from facebook and manage to sort it out ✌️

Just an update, there's no change after adding the client token to info.plist

**Comment by leticiamrosa** [comment] 2021-11-10 17:44
Hi guys!

We have the same problem here with the login, but this just happens when we try to login with Android. After looking for the issue we notice we already receive a Facebook e-mail with this message: 

Facebook alert e-mail:
> To prevent a disrupted user experience, please ensure you are using the SDK, have updated to version 8.2+, and remove any overrides in Login Behavior during login (i.e., using LoginBehavior.WEB_VIEW_ONLY).

[Link information on Facebook Dev Blog](https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/)

After checking the lib `react-native-fbsdk-next` code we found some overrides in Login Behavior, like that:
![Captura de Tela 2021-11-10 às 14 30 36](https://user-images.githubusercontent.com/20244584/141164092-1a94c7b4-3782-4499-ab11-170dd55e82e1.png)
 
Maybe this is being called somewhere? Any tips guys? 🥺

**Comment by mikehardy** [comment] 2021-11-10 19:43
> Maybe this is being called somewhere? Any tips guys? pleading_face

You can clone the repo and `grep -r LoginBehavior src android ios` yes?

I think that's something we *allow* people to call, I'm not sure we actually call it anywhere internally, so I'd check your project code. I haven't looked though

**Comment by yosukapro** [comment] 2021-11-11 09:55
I'm facing same issue and stuck with it for 3 days.
Right now it happen only on iOS, I've following new Quickstart setup Facebook sdk for iOS. But still not working

**Comment by andrewdazs** [comment] 2021-11-11 13:00
I am also having this problem on iOS for 4 days. I reviewed the implementation and everything is correct, I haven't changed anything since the problem started. Does anyone have a solution?

**Comment by bsonmez** [comment] 2021-11-12 17:46
I spent hours and could not find anything related to the issue. Is there someone who could find a solution?

**Comment by mikehardy** [comment] 2021-11-12 17:57
The general feeling on this thread is that facebook is doing *something* on a specific project basis. I just logged out and in to my app again via facebook and it worked, iOS and Android. I haven't released the v5 version from here (with facebook-ios-sdk v11 and facebook-android-sdk v12) so it's the older native versions, but this appears project specific.

There is no further information I'm aware of.

**Comment by Aung-Myint-Thein** [comment] 2021-11-15 13:54
https://developers.facebook.com/support/bugs/1259584084454192

https://developers.facebook.com/support/bugs/570255687414820

Hey guys, our app is also disabled. After a few emails with Facebook and some research, found out that a lot of users are facing the same issue and it is already reported to Facebook and hopefully, it will be fixed soon..

**Comment by mikehardy** [comment] 2021-11-15 14:08
Thanks for those links! The first one in particular looks like it's the one to follow https://developers.facebook.com/support/bugs/1259584084454192 - but there's nothing really useful there yet.

For the avoidance of doubt - this still appears 100% an upstream issue. Normally I'd close this as this will not result in a change in this module, but I know this is affecting a lot of people and leaving it open may help new people find this for now.

Fingers crossed for all you affected people that this is resolved for you soon

**Comment by Aung-Myint-Thein** [comment] 2021-11-17 11:38
Thanks @mikehardy 

Hello fellow devs, I managed to get our app enabled. Luckily, we are using OTA (expo-updates) and hence, I disabled Facebook Login in our iOS app by checking `Platform.OS`.  Then, I sent an appeal to Facebook that I have dropped "Login with Facebook" on iOS since this issue is from Facebook and we cannot solve it. I also requested to enable our app again so that our Android users can continue using "Login with Facebook" since the issue is not on Android. And it is enabled! :D 

I will keep an eye on the bug reported in Facebook and will enable "Login with Facebook" on iOS using OTA after it is resolved. I know you all won't have the same set up and the same freedom. Hope this can give one method to enable the Facebook app again. Thanks for reporting. Happy coding!

**Comment by mikehardy** [comment] 2021-11-17 11:54
That's crazy, so basically the resolution strategy is "hostage taking" (by effectively taking their revenue stream - user data - and removing it) ! A crazy way to negotiate but if it works, it works...

**Comment by Aung-Myint-Thein** [comment] 2021-11-17 11:57
> That's crazy, so basically the resolution strategy is "hostage taking" (by effectively taking their revenue stream - user data - and removing it) ! A crazy way to negotiate but if it works, it works...

Yea and we can afford this method because our iOS users are less than 10% and our Android users are over 90%. Moreover, we are also using other Facebook APIs such as chatbot, marketing etc and we cannot halt the whole operation just because their tech team messed up for iOS :( .. so, we took this route. :D

**Comment by approached** [comment] 2021-11-21 21:58
Same problem :-(

**Comment by gigeos** [comment] 2021-11-23 13:44
Hie! For my part, I tried with `react-native-fbsdk-next` v4.6.0 (Android SDK 9.0/iOS SDK 9.3) and I resolved the issue on Android by adding `user_friends` in permissions
```
await LoginManager.logInWithPermissions([
        'public_profile',
        'email',
        'user_friends',
      ]);
```
BUT it doesn't work yet on iOS

**Comment by banduk** [comment] 2021-11-23 21:41
We're having the same issue. 

One thing we noticed is that before logging in using the ios app we manage to login using our web app. After logging ing using the ios app the web login start to fail. Than we noticed that everytime we login using the ios app an `openid` permission is added to the user (we checked the permissions of the test user and we concluded the same happens to our dev users)

We filed a [facebook bug](https://developers.facebook.com/support/bugs/2747062265594445/) and a [stackoverflow](https://stackoverflow.com/questions/70088079/facebook-ios-sdk-login-unsupported-request) issue to try to speedup the process as we're being really impacted by this bug.

Now we're testing your approach @gigeos . We'll let you know if it works

**Comment by banduk** [comment] 2021-11-24 13:32
@gigeos It **partially** worked for me.

It works when we login through Safari browser (with user logged in) but it does not work when done through Facebook App.

Could you please confirm if the same happens in your side?

**Comment by vvusts** [comment] 2021-11-25 13:12
I am also started to experience same issue. 
Android is fine but I get same error on ios dsimulator/device debug/release mode.
I am using fbsdk-next 6.1.1 on RN0.63.4
Production app work fine so it's not account issue. This started single I switched fbsdk to fbsdk-next.

**Comment by mikehardy** [comment] 2021-11-25 13:16
Your assertion about it not being an account issue is unproven.
Moving to higher SDKs can use different capabilities and that may not interoperate well with some setting or flag in your account, I'm not sure.

What I do know for sure is that I am using the current versions and everything is fine for me in testing versions of my app (different backends), production versions of my app, and the example app here with FB example test accounts.

From my perspective, this is still an account issue and my assertion has all the data above plus my experience as basis, sorry

I don't see anything actionable here on the module level

**Comment by vvusts** [comment] 2021-11-25 13:18
Ok, I will try to investigate on facebook side. But question. 
Is it possible to use 6.1.1 and set it to use lower FBSDK version?

**Comment by mikehardy** [comment] 2021-11-25 13:34
Untested, could work. You may examine the PRs that implemented support for the lower SDKs and via patch-package do literally anything, including reversing tiny changes if needed in order to make the old SDKs work. I wouldn't recommend that as a permanent strategy but adopting open source means it's *possible* and can mitigate business impact, so it's not too crazy an idea. This is the reason to use open source really - can hack at things to make them run at least...

**Comment by banduk** [comment] 2021-11-25 14:40
More information about our case:

We removed Facebook integration for the iOS app because we could not keep going without Facebook login for Android users. The app was reactivated and, after that, we generated a new production build and it's working as it should

We're still waiting for Facebook's response.

**Comment by vvusts** [comment] 2021-11-25 15:00
I tried all down to 9.0.1 it doesn't work. I will try to contact facebook support.

**Comment by vladakg85** [comment] 2021-11-26 17:10
After contacting fb support it works on fbsdk 12.1. So it was not library issue.

**Comment by mikehardy** [comment] 2021-11-26 18:59
I just checked the linked bug - it appears the process is: Go to Facebook Developers site, file an issue for your specific app, work through their support channel.

Sounds like fun! I'm kidding of course, but that is the way everyone is resolving these. Good luck

**Comment by martinsinghk** [comment] 2021-12-09 04:01
To follow up with the solution provided by @gigeos, our app has also encountered a similar issue in version 6.1.1.
`  "message":"SERVER_ERROR: [code] 1675030 [message]: ..."`

Surprisingly, we were able to make it through with an additional empty string supplied to the permission array:
`['public_profile', 'email', '']`

In our case, the problem only happened in Android side. Although we haven't dug really deep into the source code, it looks very likely an issue in `com.facebook.login.LoginManager`.

**Comment by mikehardy** [comment] 2021-12-09 12:10
Definitely looks like something to chase upstream - check their issues list + pr list + https://github.com/facebook/facebook-android-sdk/

If it has no implications on our side (that is, is tested and has no breaking change for any use cases) **AND** there was a bug logged upstream we could hook it to, we could implement a temporary workaround here that appends that.

**Comment by thebergamo** [comment] 2021-12-14 08:24
As it seems to be an upstream issue I'm closing this thread. In case anyone has a different view of it, please file a new issue.

**Closed by thebergamo** 2021-12-14 08:24 UTC
Labels: wontfix, upstream
