### ISSUE TITLE
Facebook SDK is initialized immediately (when using Expo) even though it should not be 

### ISSUE THREAD

**Issue by kopfnick** [thebergamo/react-native-fbsdk-next#295] opened 2022-07-29 09:27 UTC
Facebook disabled the automatic initialization of the SDK a while ago (https://github.com/facebook/facebook-ios-sdk/commit/dfd2977b8d2221dea184cfccd540138a29eacd06). This is especially important for GDPR compliance since you have to get user consent before the SDK does any requests to the Facebook backends.

We tried implementing the wrapper and set all available options to false but saw that the SDK immediately "phones home" when opening the app in the simulator:

![image](https://user-images.githubusercontent.com/13811487/181729698-b69681d7-f112-48fb-b422-c4f7d6c1557c.png)

When debugging we ultimately found out that it only happens when using Expo.
It seems the Expo config plugin is always used because of https://github.com/thebergamo/react-native-fbsdk-next/blob/master/expo-module.config.json and it always adds the initialization to the AppDelegate regardless of what the JS configuration is.

This file is executed then even if it should not be because we set isAutoInitEnabled to FALSE: https://github.com/thebergamo/react-native-fbsdk-next/blob/master/ios/ExpoAdapterFBSDKNext/FacebookAppDelegate.swift

**Comment by mikehardy** [comment] 2022-07-30 22:12
Hi there! Expo support is contributed by users, none of the earlier maintainers use Expo, and I certainly don't. If this is important to you and you can figure out how to alter the plugin to do things optionally (perhaps based on an app.json setting?) and post a PR, we can get it merged and released

**Comment by barthap** [comment] 2022-08-05 13:39
I'm not using FB SDK so I'll only speak about the Expo part here.

> This file is executed then even if it should not be because we set isAutoInitEnabled to FALSE: `FacebookAppDelegate.swift`

The AppDelegate subscriber is supposed to be ALWAYS executed, regardless of any options. This behaves the same as you'd just added this code to `AppDelegate.mm`. If you compare this file's code to installation instructions from this library's README, you can see that it does precisely the iOS installation instruction and nothing more, so the problem is not here.
If you did it manually, without Expo, you'd have to manually add these lines to AppDelegate anyway.

The `isAutoInitEnabled` seems to add some option to the `ios/Info.plist` file - see:
https://github.com/thebergamo/react-native-fbsdk-next/blob/63f9c6f6d61d99134c648809346d6fc4fe645387/plugin/src/withFacebookIOS.ts#L70

So this is where I'd start looking for - if this entry is not added to `Info.plist`, then it's Expo plugin's fault. But if it's not, then it means that [RN] Facebook SDK somehow doesn't care about this entry, but I as I said before, I don't know much about this lib.

**Comment by baochungit** [comment] 2022-08-07 07:20
Is the `isAutoInitEnabled` set to true in app.json?

**Closed** 2022-09-13 11:50 UTC
Labels: wontfix
