### ISSUE TITLE
UIWebview deprecation

### ISSUE THREAD

**Issue by jaikantshikray** [thebergamo/react-native-fbsdk-next#302] opened 2022-08-21 07:56 UTC
My app got rejected as i push to testflight because of the deprecation of UiWebView component that this library might be using i have even tried to update to latest version of this library but still facing the issue and when i run grep "UiWebView" it shows bellow message 

Binary file Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/tvos-arm64/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches

please help me resolve this issue my release is struck atm

**Comment by mikehardy** [comment] 2022-08-21 16:46
I suspect something is still not correct somehow, as the upstream repo has a bunch of these issues, all resolved long ago with versions we have long ago started using:

https://github.com/facebook/facebook-ios-sdk/issues/1290

https://github.com/facebook/facebook-ios-sdk/issues?q=is%3Aissue+UIWebView

I haven't received deprecation warnings for this and my apps are not being rejected right now either

If you can produce a reproduction we can reopen but here's what I did just now - I took my work app (which uses this module, in its current version) and rebuilt it (just to be sure) and resubmitted it to TestFlight, and it worked.

I suspect that the module uses UIWebView in test scenarios only (learned from reading the upstream issues in facebook-ios-sdk) but the symbols are not included in release builds. Because TestFlight takes my builds just fine but I also receive hits on a grep for UIWebView

T;DR: I can grep and see the symbols, but I just uploaded a build to TestFlight to check this issue, and it was accepted just fine. I suspect you have something else using UIWebView

**Comment by jaikantshikray** [comment] 2022-08-21 23:40
yes there is another library that is having Uiwebview in grep response that is react native admob and this issue seems to happen after i updated react native fbsdk to latest version

**Comment by mikehardy** [comment] 2022-08-22 00:29
Ironically, I am also the maintainer of react-native-google-mobile-ads (the current best-I-think(?) react-native admob implementation) and no one has complained of this either.

I'm really not sure what to say. I was afraid this might true so I *personally* did a fresh build of one of my work projects that uses react-native-fbsdk-next, with the current version in it, and pushed it to TestFlight. It worked

No one else has complained of this either. Maybe I am missing something but I've got zero ability to reproduce and I have tested it directly. I'm sure this is frustrating, I hate it when I am faced with problems like these which is why I tested it personally, but that doesn't help you much on the other side. I just can't think of anything actionable here for me or anyone else to do

**Comment by jaikantshikray** [comment] 2022-08-22 05:09
if this helps , this is the output of grep -r UIWebView ios/Pods/*

see it points the fbsdk and Google Admob sdk 

ios/Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
Binary file ios/Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/tvos-arm64/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ios/Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/tvos-arm64_x86_64-simulator/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ios/Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/ios-arm64_x86_64-simulator/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ios/Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/ios-arm64_x86_64-maccatalyst/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ios/Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/ios-arm64/dSYMs/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ios/Pods/FBSDKGamingServicesKit/XCFrameworks/FBSDKGamingServicesKit.xcframework/ios-arm64_x86_64-simulator/dSYMs/FBSDKGamingServicesKit.framework.dSYM/Contents/Resources/DWARF/FBSDKGamingServicesKit matches
Binary file ios/Pods/FBSDKGamingServicesKit/XCFrameworks/FBSDKGamingServicesKit.xcframework/ios-arm64_x86_64-maccatalyst/dSYMs/FBSDKGamingServicesKit.framework.dSYM/Contents/Resources/DWARF/FBSDKGamingServicesKit matches
Binary file ios/Pods/FBSDKGamingServicesKit/XCFrameworks/FBSDKGamingServicesKit.xcframework/ios-arm64/dSYMs/FBSDKGamingServicesKit.framework.dSYM/Contents/Resources/DWARF/FBSDKGamingServicesKit matches
Binary file ios/Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/tvos-arm64/dSYMs/FBSDKLoginKit.framework.dSYM/Contents/Resources/DWARF/FBSDKLoginKit matches
Binary file ios/Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/tvos-arm64_x86_64-simulator/dSYMs/FBSDKLoginKit.framework.dSYM/Contents/Resources/DWARF/FBSDKLoginKit matches
Binary file ios/Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/ios-arm64_x86_64-simulator/dSYMs/FBSDKLoginKit.framework.dSYM/Contents/Resources/DWARF/FBSDKLoginKit matches
Binary file ios/Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/ios-arm64_x86_64-maccatalyst/dSYMs/FBSDKLoginKit.framework.dSYM/Contents/Resources/DWARF/FBSDKLoginKit matches
Binary file ios/Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/ios-arm64/dSYMs/FBSDKLoginKit.framework.dSYM/Contents/Resources/DWARF/FBSDKLoginKit matches
Binary file ios/Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/tvos-arm64/dSYMs/FBSDKShareKit.framework.dSYM/Contents/Resources/DWARF/FBSDKShareKit matches
Binary file ios/Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/tvos-arm64_x86_64-simulator/dSYMs/FBSDKShareKit.framework.dSYM/Contents/Resources/DWARF/FBSDKShareKit matches
Binary file ios/Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/ios-arm64_x86_64-simulator/dSYMs/FBSDKShareKit.framework.dSYM/Contents/Resources/DWARF/FBSDKShareKit matches
Binary file ios/Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/ios-arm64_x86_64-maccatalyst/dSYMs/FBSDKShareKit.framework.dSYM/Contents/Resources/DWARF/FBSDKShareKit matches
Binary file ios/Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/ios-arm64/dSYMs/FBSDKShareKit.framework.dSYM/Contents/Resources/DWARF/FBSDKShareKit matches
Binary file ios/Pods/Google-Mobile-Ads-SDK/Libraries/libGoogleMobileAds.a matches
Binary file ios/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks/GoogleMobileAds.framework/GoogleMobileAds matches

**Comment by mikehardy** [comment] 2022-08-22 12:53
Unfortunately it does not help, as mentioned above I have seen this output - I also did the grep you did.

That is what made me fear I would also see a rejection from TestFlight so much that I tried it myself.

>  personally did a fresh build of one of my work projects that uses react-native-fbsdk-next, with the current version in it, and pushed it to TestFlight. It worked

I cannot reproduce it. No one else is reproducing it. I'm not sure what more I can do

**Comment by jaikantshikray** [comment] 2022-08-31 03:45
i have upgraded React native version to 0.69 and upgraded react native gesture handler library and netinfo and device info library to resolve this issue

**Comment by usman-khan-1** [comment] 2023-10-14 06:05
> Ironically, I am also the maintainer of react-native-google-mobile-ads (the current best-I-think(?) react-native admob implementation) and no one has complained of this either.
> 
> I'm really not sure what to say. I was afraid this might true so I _personally_ did a fresh build of one of my work projects that uses react-native-fbsdk-next, with the current version in it, and pushed it to TestFlight. It worked
> 
> No one else has complained of this either. Maybe I am missing something but I've got zero ability to reproduce and I have tested it directly. I'm sure this is frustrating, I hate it when I am faced with problems like these which is why I tested it personally, but that doesn't help you much on the other side. I just can't think of anything actionable here for me or anyone else to do

@mikehardy This rejection is only coming up for new apps. Screenshot attached 
<img width="1029" alt="Screenshot 2023-10-14 at 9 33 53 AM" src="https://github.com/thebergamo/react-native-fbsdk-next/assets/1204852/720a8261-9d28-40ce-9774-41a47d14dfd2">

Let me know if I can provide you more insights/details. thank you

**Comment by mikehardy** [comment] 2023-10-18 21:54
@usman-khan-1 that appears to be new - and very important to know - information:

> This rejection is only coming up for new apps

I was using an existing app and just pushing a new version. I have not personally tried with a new app

Note that this report is fairly old - I have not done any maintenance in this repo in a while, it is possible that new versions of the facebook-ios-sdk no longer suffer this problem, and separately it is possible that we either have already adopted them here or we could adopt them here and then things will be fixed.

With apologies that I have not done the research myself, I would appreciate if anyone else did pursue that line of thought - specifically 1) is this already fixed in facebook-ios-sdk and if not why not and pursue... 2) once facebook-ios-sdk has fixed it upstream (or if it is already fixed) adopt the corresponding facebook-ios-sdk version here...

**Comment by usman-khan-1** [comment] 2023-11-01 14:02
@mikehardy Let me also do some due diligence and see where the problem exists. fingers crossed

**Comment by mikehardy** [comment] 2023-11-01 14:13
16.1.3 is the facebook-ios-sdk we pull in https://github.com/thebergamo/react-native-fbsdk-next/blob/36a762af896bc4ed2dd08b1f361267f107e830ed/react-native-fbsdk-next.podspec#L4

16.2.1 is current but I don't see any mention of UIWebview in the release notes, so I'm just not sure https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1621

The last time it was mentioned was long long long long ago in v5 upstream https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#changed-20

> Replaced UIWebView with WKWebView as Apple will stop accepting submissions of apps that use UIWebView APIs

So, this is unexpected at least

**Closed** 2023-12-09 00:30 UTC
Labels: wontfix
