### ISSUE TITLE
IOS build failed with FBSDKCoreKit/FBSDKCoreKit.modulemap not found

### ISSUE THREAD

**Issue by Navipro70** [thebergamo/react-native-fbsdk-next#72] opened 2021-07-13 17:22 UTC
## 🐛 Bug Report

I need to build ios archive  from command line for detox testing. All works perfect when running on simulators/real devices, but on archive build (command in code snippet), I see next error:

```
<unknown>:0: error: module map file '/Users/dmitry/Projects/AwesomeApp/ios/build/Build/Products/Release-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/dmitry/Projects/AwesomeApp/ios/build/Build/Intermediates.noindex/PrecompiledHeaders/AwesomeApp-Bridging-Header-swift_6WC6263DQMVA-clang_2T5L1QNOD8N2C.pch' for bridging header '/Users/dmitry/Projects/AwesomeApp/ios/AwesomeApp-Bridging-Header.h'
3 errors generated.
```

## Additional info

My `Bridging-Header.h` is empty file, I already have `File.swift` and trying to clear all cache in project.

## To Reproduce

On project with setuped react-native-fbsdk-next correctly, try to build ios archive (command line in code snippet).

## Expected Behavior

Get builded ios app in ios/build.

## Code Snippet
```
xcodebuild -project ios/AwesomeApp.xcodeproj -scheme AwesomeApp -configuration Release -sdk iphonesimulator VALID_ARCHS=arm64 ARCHS=arm64 -derivedDataPath ios/build
```
## Environment
```
Xcode: 12.5
Mac: Apple silicon m1
    
"react-native": "0.64.0"
"react-native-fbsdk-next": "^4.3.0"
```

**Comment by mikehardy** [comment] 2021-07-13 17:41
Hi there :wave: - I also am not able to build this library on an M1 mac. Just got one in the house for the first time a few days ago and noticed it immediately, but was unable to hack through it. That isn't a great sign since I help maintain the library :sweat_smile: but it's important to say because you will most likely need to work through it yourself, possibly looking into the upstream library (that is: try to make a minimal app using nothing but the upstream facebook-ios-sdk imported into the simplest possible Objective-C hello world app to see if it works)

I'm also stuck on this but without time to actively work on it, so I'm really curious to hear any progress and I can collaborate on getting PRs merged etc but I won't be able to advance it myself for a while at least (like, weeks - since I still have intel macs to build on)

**Comment by Navipro70** [comment] 2021-07-13 17:51
@mikehardy Thanks for the quick answer with info)

I'm not sure, but maybe one of developers from current project with not m1 proc also have this problems, I gonna write as fast as possible

**Comment by mikehardy** [comment] 2021-07-13 21:20
It works fine for me with Intel macs. It only fails on Apple Silicon / M1 macs for me.

**Comment by enriqueao** [comment] 2021-07-27 17:50
@Navipro70  Open Xcode with Rosetta fix my issue 

Applications -> Xcode -> Get Info -> Open With Rosetta

maybe help this [Apple silicon support #295](https://github.com/react-native-community/discussions-and-proposals/issues/295#issuecomment-751307863) 

## Environment
```
Xcode 12.5
M1
"react-native": "0.60.1",
"react-native-fbsdk-next": "3.1.0",
```

**Comment by mikehardy** [comment] 2021-07-27 20:41
Apple Silicon won't be natively supported (that is, with Flipper and Hermes working) on Apple Silicon until the 0.65 release that's in rc3 status right now. FBSDK (this module) still has issues as well and needs a forward port to v11 (#55) most likely before it will work. I would love :pray: if anyone had time to do that and post it up, it's a real issue and needs help

**Comment by dgreasi** [comment] 2021-09-21 14:15
Having a similar issue after updating to Xcode 13:

```
- module map file '/Users/dgreasidis/Library/Developer/Xcode/DerivedData/VSale-bipjdhkuiwimlpbbzfqwtjchvjnf/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found

- module map file '/Users/dgreasidis/Library/Developer/Xcode/DerivedData/VSale-bipjdhkuiwimlpbbzfqwtjchvjnf/Build/Products/Debug-iphonesimulator/FBSDKLoginKit/FBSDKLoginKit.modulemap' not found

- module map file '/Users/dgreasidis/Library/Developer/Xcode/DerivedData/VSale-bipjdhkuiwimlpbbzfqwtjchvjnf/Build/Products/Debug-iphonesimulator/FBSDKShareKit/FBSDKShareKit.modulemap' not found

- module map file '/Users/dgreasidis/Library/Developer/Xcode/DerivedData/VSale-bipjdhkuiwimlpbbzfqwtjchvjnf/Build/Products/Debug-iphonesimulator/YogaKit/YogaKit.modulemap' not found

- Command PrecompileSwiftBridgingHeader emitted errors but did not return a nonzero exit code to indicate failure
```

## Environment

```
Xcode 13 (Intel Mac)
"react-native": "0.63.3",
"react-native-fbsdk-next": "^4.3.1",
```

**Comment by mikehardy** [comment] 2021-09-21 16:38
I'm pretty sure I tested this module with Xcode 13 betas prior to general release and it was fine.
With a major Xcode release you may need `npx react-native-clean-project` to purge out the Xcode DerivedData folder though. Your error just looks like stale Xcode stuff to me.

**Comment by mikehardy** [comment] 2021-09-21 17:12
Yeah - I'm downloading it now from the App Store so I'll be able to confirm shortly but you know it's huge :pig2: so it takes a while for me to download it on my connection :smile:

**Comment by mikehardy** [comment] 2021-09-22 00:04
Okay, strange news as this means we have varying reproductions, but with react-native-fbsdk-next I have no problem with Xcode 12.5.1 and Xcode 13. I cannot reproduce this problem, having now done successful builds this afternoon on multiple machines. Something is going on in your local environment I guess ?

In order to troubleshoot further we'll need to see a reproduction repo that starts from `npx react-native init FBSDKerror`, adds the module, and still fails.

I would definitely try updating to react-native 0.65.1 though prior to spending much time troubleshooting, I don't think Xcode13 is supported back that far and it would be a shame to waste time chasing "ghost bugs" that were already fixed.

**Comment by Navipro70** [comment] 2021-09-23 20:37
@mikehardy 
Tested on RN 0.64.1, XCode 12.5, Mac m1. All works nice and I managed to build archive application for testing (after 3 f*cking days 😅). 
I think that this issue is not related to m1 proc, because I've fixed all with [this hack](https://github.com/facebook/react-native/issues/31480#issuecomment-902912841) and also with [this hack](https://github.com/facebook/react-native/issues/28483#issuecomment-610839293)

**Comment by mikehardy** [comment] 2021-09-23 21:51
Hahaha - my hacks are everywhere! They're actually baked in to react-native 0.66 until all the underlying issues are fixed ;-)
Happy to hear you have it working and rest assured the underlying issues *are* receiving attention, we're not just automating the workarounds (though that will help too). Cheers

**Closed by mikehardy** 2021-09-23 21:51 UTC
Labels: bug, no reproduction

**Comment by dgreasi** [comment] 2021-09-24 09:09
> Okay, strange news as this means we have varying reproductions, but with react-native-fbsdk-next I have no problem with Xcode 12.5.1 and Xcode 13. I cannot reproduce this problem, having now done successful builds this afternoon on multiple machines. Something is going on in your local environment I guess ?
> 
> In order to troubleshoot further we'll need to see a reproduction repo that starts from `npx react-native init FBSDKerror`, adds the module, and still fails.
> 
> I would definitely try updating to react-native 0.65.1 though prior to spending much time troubleshooting, I don't think Xcode13 is supported back that far and it would be a shame to waste time chasing "ghost bugs" that were already fixed.

Tested on latest react-native 0.65.1 and Xcode 13. Seems that the error occurs from 2 different libraries but if the fbsdk-next is installed we will see the 'FBSDKCoreKit/FBSDKCoreKit.modulemap not found'.

Seems independent.

Just adding here the actual reference of the issue [here](https://github.com/software-mansion/react-native-reanimated/issues/2448)

**Comment by mikehardy** [comment] 2021-09-24 13:39
Have you made sure that the Podfile iOS deployment version you are using matches the iOS deployment version set in your app settings via Xcode? I saw an issue somewhere else about modulemap not found solved by that. Also perhaps `npx react-native-clean-project` if I have not already suggested that + you have not already done it

**Comment by dgreasi** [comment] 2021-09-24 14:21
Already done that. No result. Nevertheless, after downgrading Cocoapods the resulting error is quite different.

```
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

...


** BUILD FAILED **


The following build commands failed:
        Ld /Users/dgreasidis/Library/Developer/Xcode/DerivedData/ReactNativeError-bxbpbdmyjeetrebwqjvtywrobiue/Build/Products/Debug-iphonesimulator/ReactNativeError.app/ReactNativeError normal (in target 'ReactNativeError' from project 'ReactNativeError')
(1 failure)

```

Investigating more...

**Comment by mikehardy** [comment] 2021-09-24 14:24
Oh, the Swift errors :-) - "pick me pick me :raised_hand_with_fingers_splayed: " - looks like this workaround is needed, it resolves swift errors for me https://github.com/invertase/react-native-firebase/blob/47d226526fec4dcee6edc5f5c2e37f430e91cae9/tests/ios/Podfile#L53

Please note that I have no problems building this lib on Xcode 12.5.1 or Xcode 13 with Cocoapods 10.x or 11.x, so something is still not happy in your local environment.

**Comment by dgreasi** [comment] 2021-09-24 14:34
Yeah the problem is not in the fbsdk library. Your proposition didn't work either.

**Comment by mikehardy** [comment] 2021-09-24 15:02
As part of my efforts to qualify react-native 0.66 I actually tested react-native-fbsdk-next during compile testing, I explicitly did this on M1 and Intel macs running Xcode 12.5.1 and Xcode 13, with hermes on and off, in debug and release configurations and everything worked:

```
npx react-native init FB66Test --version 0.66.0-rc.4
cd FB66Test
yarn add react-native-fbsdk-next
npx pod-install
yarn ios
```

Some days it feels like I do nothing *but* compile testing, and I'm surprised none of this stuff is working for you. It really should be working

**Comment by rossjohnsonMP** [comment] 2021-11-03 15:00
I unfortunately also have this same issue, intel MacOS 11, Xcode 13.1, RN 66 + 65. Also same issue on github actions, seen lots of resolutions being cache issues or restarting laptop which clearly don't apply there. Must be something in my set up but I have no idea what or where to begin to debug.

yarn ios works fine but build_app through fastlane does not.

Anything I can do to help repro this, please let me know!

```
error: module map file 'BuildProductsPath/Release-iphoneos/FBSDKLoginKit/FBSDKLoginKit.modulemap' not found
error: module map file 'BuildProductsPath/Release-iphoneos/FBSDKShareKit/FBSDKShareKit.modulemap' not found
```

**Comment by PaperMonster** [comment] 2021-11-16 04:40
> Have you made sure that the Podfile iOS deployment version you are using matches the iOS deployment version set in your app settings via Xcode? I saw an issue somewhere else about modulemap not found solved by that. Also perhaps `npx react-native-clean-project` if I have not already suggested that + you have not already done it

I had different iOS deployment versions (updated Podfile to iOS 11 but forgot to update Xcode project side while upgrading to RN 0.66). Set them to the same version fixed the problem for me. Thank you for keeping me from losing my hair!

**Comment by mikehardy** [comment] 2021-11-16 12:10
This would be funny if it weren't true - I left that hint in September then just a couple weeks ago ran into it AGAIN and had forgotten. Had to re-learn it, lost some hair, uggh :-)

**Comment by rossjohnsonMP** [comment] 2021-11-16 13:38
Ah gutting 🤦  exact same issue for me and I completely missed @mikehardy's solution thank you @PaperMonster

**Comment by viscosityron** [comment] 2022-02-10 20:52
> I'm pretty sure I tested this module with Xcode 13 betas prior to general release and it was fine. With a major Xcode release you may need `npx react-native-clean-project` to purge out the Xcode DerivedData folder though. Your error just looks like stale Xcode stuff to me.

Mine was Definitely just stale Xcode stuff. Thanks a million!
